### ISSUE TITLE
interpret_cmd

### ISSUE THREAD

**Issue by kmsmi** [Tyill/zmey#1]
Извиняюсь что пишу сюда. На одном форуме нашел тему про интерпретатор.
Судя по описанию это то что мне нужно. Но ссылка на исходники не рабочая.
Можно как то их получить?
https://www.cyberforum.ru/cpp-beginners/thread1815502.html

**Comment by Tyill** [comment]
Здравствуйте. 
Ды можно конечно, но лучше бы вы вот этим воспользовались:
http://www.lua.ru/

К нему есть хороший плагин для плюсов:
https://github.com/vinniefalco/LuaBridge

Мне раньше не хотелось (да и времени не было) разбираться с lua, поэтому эту поделку написал.


[interpret_cmd.zip](https://github.com/Tyill/zmey/files/5671779/interpret_cmd.zip)

**Comment by kmsmi** [comment]
Спасибо большое. Lua мне не подойдет, интерпретатор нужно встроить в контроллер. Lua для этого слишком прожорлив.

**Comment by kmsmi** [comment]
Не посмотрел сразу, Но по ссылке нету исходников. А мне нужны именно они.
